### ISSUE TITLE
update? 2nd…

### ISSUE THREAD

**Issue by Shea690901** [zesstra/MorgenGrauen#3]
According to `progit`, which can be found either under http://progit.org/ or https://github.com/progit/ , you might try `git format-patch` on the sending side (your private repository) and `git am` on the receiving side (the public one).
With `format-patch` git exports all commits seperatly as patch-sets together with complete meta-info, like author and commit-message, while `am` tells git to replay those patches using the supplied meta-info for commiting the just applied patches…
Definitely something you might want to look into ;)

**Comment by zesstra** [comment]
Thanks for the suggestion. I know git format-patch (and use it often)... However as I said last year: I don't have a primary git repo, where I could just use git format-patch. I would have to export the commits, filter them to exclude the private commits (also, the risk to publish something by accident here is to high) and apply them to this git repository. Currently, I don't have time for this. I am already far behind the more pressing issues in MG and LDMud.
 
But if you are interested in the MG library: I invite you to use the daily snapshots of the MG library at ftp://mg.mud.de/Software/MudLib/ instead.
